### ISSUE TITLE
graphic 이슈작성

### ISSUE THREAD

**Issue by kimneusi** [kimneusi/case3#3]
1.graphic 브런치를 만들었습니다.
2.graphic 브런치에 graphic.txt 파일을 생성한 후 add, commit 및 push 작업을 진행했습니다.
3.graphic 브런치에 graphic2.txt 파일을 추가적으로 생성한 후  add, commit 및 push 작업을 진행했습니다.
4.원격저장소에 pull request를 작성했습니다.

**Comment by Syurie** [comment]
확인하였습니다
